get http://localhost:9000/ratemovie/


###

post http://localhost:9000/ratemovie/find
Content-Type: application/json

{
     "movieId": "581389"
}


###

post http://localhost:9000/ratemovie/add/
Content-Type: application/json

{
    "movieId":"1111",
    "movieTitle":"Lord Of the Ring",
    "movieRunTime":"128",
    "movieRate":"4",
    "movieComment":"movie sucks"
}

###
delete http://localhost:9000/ratemovie/delete/
Content-Type: application/json

{
     "movieId":"399566"
}

###
PATCH  http://localhost:9000/ratemovie/edit
Content-Type: application/json

{
     "movieId":"asd",
     "movieRate":"3"
}

###

PATCH  http://localhost:9000/ratemovie/editcomment
Content-Type: application/json

{
     "movieId":"399566",
     "movieComment":"movie sucksdddddddddddddddddddddddddddddddddd"
}